export const questions = [
  {
    id: "q1",
    zPosition: -120,
    questionImage: "/images/q1.png",
    options: [
      {
        id: "q1-opt1",
        text: "কপৌ ফুল",
        image: "/images/gamusa3.png",
        model: "/models/kopou.glb",
        correct: true,
      },
      {
        id: "q1-opt2",
        text: "গোলাপ",
        image: "/images/umbrella.jpg",
        model: "/models/rose.glb",
        correct: false,
      },
      {
        id: "q1-opt3",
        text: "সূৰ্যমুখী",
        image: "/images/shoes.jpg",
        model: "/models/sunflower.glb",
        correct: false,
      },
    ],
  },
  {
    id: "q2",
    zPosition: -270,
    questionImage: "/images/q2.png",
    options: [
      {
        id: "q2-opt1",
        text: "হাতী",
        image: "/images/cow.jpg",
        model: "/models/elephant.glb",
        correct: false,
      },
      {
        id: "q2-opt2",
        text: "এশিঙীয়া গঁড়",
        image: "/images/bird.jpg",
        model: "/models/rhino.glb",
        correct: false,
      },
      {
        id: "q2-opt3",
        text: "বাঘ",
        image: "/images/veins.png",
        model: "/models/tiger.glb",
        correct: true,
      },
    ],    
  },

  {
    id: "q3",
    zPosition: -420,
    questionImage: "/images/q3.png",
    options: [
      {
        id: "q3-opt1",
        text: "হাতী",
        image: "/images/bear.png",
        model: "/models/elephant.glb",
        correct: false,
      },
      {
        id: "q3-opt2",
        text: "এশিঙীয়া গঁড়",
        image: "/images/axe.jpg",
        model: "/models/rhino.glb",
        correct: true,
      },
      {
        id: "q3-opt3",
        text: "বাঘ",
        image: "/images/gibbon.png",
        model: "/models/tiger.glb",
        correct: false,
      },
    ],
  },
  {
  id: "q4",
  zPosition: -570,
  questionText: "পাত আছে ডাল নাই, কথা আছে মাত নাই ?",
  answer: "কিতাপ",
  questionImage: "/images/q4.png",
  options: [
    {
      id: "q4-opt1",
      text: "কিতাপ",
      image: "/images/book.png",
      model: "/models/q4-opt1.glb",
      correct: true,
    },
    {
      id: "q4-opt2",
      text: "খাতা",
      image: "/images/tree.jpg",
      model: "/models/q4-opt2.glb",
      correct: false,
    },
    {
      id: "q4-opt3",
      text: "কাকত",
      image: "/images/birds.jpg",
      model: "/models/q4-opt3.glb",
      correct: false,
    },
  ],
  },
  {
  id: "q5",
  zPosition: -720,
  questionText: "এক ঠেঙীয়া বগলী , নিতৌ নাচে গধূলি ?",
  answer: "নাক",
  questionImage: "/images/q5.jpg",
  options: [
    {
      id: "q5-opt1",
      text: "নাক",
      image: "/images/dheki.png",
      model: "/models/q5-opt1.glb",
      correct: true,
    },
    {
      id: "q5-opt2",
      text: "কাণ",
      image: "/images/diyas.png",
      model: "/models/q5-opt2.glb",
      correct: false,
    },  
    {
      id: "q5-opt3",
      text: "চকু",
      image: "/images/bisoni.jpg",
      model: "/models/q5-opt3.glb",
      correct: false,
    },
  ],
  },
  {
    id: "q6",
    zPosition: -870,
    questionText: "আগ তিতা গুৰি মৌ, কি কৰিছা ভাবলি বৌ ?",
    answer: "ছাতি",
    questionImage: "/images/q6.png",
    options: [
      {
        id: "q6-opt1",
        text: "ছাতি", 
        image: "/images/sugarcane.jpg",
        model: "/models/q6-opt1.glb",
        correct: true,
      },
      {
        id: "q6-opt2",
        text: "লাঠি",
        image: "/images/coffee.png",
        model: "/models/q6-opt2.glb",
        correct: false,
      },
      {
        id: "q6-opt3",
        text: "বগলী",
        image: "/images/honey.jpg",
        model: "/models/q6-opt3.glb",
        correct: false,
      },
    ],
  },
  {
  id: "q7",
  zPosition: -1020,
  questionText: "আলিয়ে আলিয়ে যায়, মূৰ দাঙি চায় ?",
  answer: "বেঙ",
  questionImage: "/images/q7.jpg",
  options: [
    {
      id: "q7-opt1",
      text: "বেঙ",
      image: "/images/injection.jpg",
      model: "/models/q7-opt1.glb",
      correct: true,
    },
    {
      id: "q7-opt2",
      text: "কাছ",
      image: "/images/ostrich.png",
      model: "/models/q7-opt2.glb",
      correct: false,
    },
    {
      id: "q7-opt3",
      text: "শামুক",
      image: "/images/turtle.png",
      model: "/models/q7-opt3.glb",
      correct: false,
    },
  ],
  },
  {
    id: "q8",
    zPosition: -1170,
    questionText: "মাত আছে মানুহ নাই, ঘৰ আছে দুৱাৰ নাই/ঘৰ আছে দুৱাৰ নাই, মাত আছে মানুহ নাই ?",
    answer: "ৰেডিঅ'",
    questionImage: "/images/q8.jpg",
    options: [
      {
        id: "q8-opt1",
        text: "ৰেডিঅ'",
        image: "/images/radio.jpg",
        model: "/models/q8-opt1.glb",
        correct: true,
      },
      {
        id: "q8-opt2",
        text: "টেলিভিছন",
        image: "/images/tv.jpg",
        model: "/models/q8-opt2.glb",
        correct: false,
      },
      {
        id: "q8-opt3",
        text: "মাইক",
        image: "/images/microphone.jpg",
        model: "/models/q8-opt3.glb",
        correct: false,
      },
    ],
  },
  {
  id: "q9",
  zPosition: -1320,
  questionText: "আছিলা গ'লা, গ'লা-আছিলা, আৰু নাহিলা।",
  answer: "দাঁত",
  questionImage: "/images/q9.jpg",
  options: [
    {
      id: "q9-opt1",
      text: "দাঁত",
      image: "/images/teeth.png",
      model: "/models/q9-opt1.glb",
      correct: true,
    },
    {
      id: "q9-opt2",
      text: "চুলি",
      image: "/images/hair.png",
      model: "/models/q9-opt2.glb",
      correct: false,
    },
    {
      id: "q9-opt3",
      text: "নখ",
      image: "/images/nails.png",
      model: "/models/q9-opt3.glb",
      correct: false,
    },
  ],
},
{
  id: "q10",
  zPosition: -1470,
  questionText: "পিটিকিলেই ভাঙে, আফলিয়ালেও নাভাঙে ।",
  answer: "কণী",
  questionImage: "/images/q10.jpg",
  options: [
    {
      id: "q10-opt1",
      text: "কণী",
      image: "/images/rice.png",
      model: "/models/q10-opt1.glb",
      correct: true,
    },
    {
      id: "q10-opt2",
      text: "নাৰিকল",
      image: "/images/egg.png",
      model: "/models/q10-opt2.glb",
      correct: false,
    },
    {
      id: "q10-opt3",
      text: "কলহ",
      image: "/images/beetle-nut.png",
      model: "/models/q10-opt3.glb",
      correct: false,
    },
  ],
},
];